server:
  baseUrl: http://localhost:3000/
  imageUrl: images/
  imageServerDir: C:/images/lab07/
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:1000/
  imageUrl: images/
---
spring:
  profiles: remote
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/